<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="106775" started-at="2020-05-20T00:07:59Z" finished-at="2020-05-20T00:09:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="106775" started-at="2020-05-20T00:07:59Z" finished-at="2020-05-20T00:09:46Z">
      <class name="com.testcases.LoginApplicationTC1">
        <test-method status="PASS" signature="init()[pri:0, instance:com.testcases.LoginApplicationTC1@7ac7a4e4]" name="init" is-config="true" duration-ms="24336" started-at="2020-05-20T05:37:59Z" finished-at="2020-05-20T05:38:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="Login()[pri:0, instance:com.testcases.LoginApplicationTC1@7ac7a4e4]" name="Login" duration-ms="82405" started-at="2020-05-20T05:38:23Z" finished-at="2020-05-20T05:39:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [Create an account] but found [CREATE AN ACCOUNT],
	We skip the email ! it is already Present expected [false] but found [true],
	expected [Your address] but found [YOUR ADDRESS]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Create an account] but found [CREATE AN ACCOUNT],
	We skip the email ! it is already Present expected [false] but found [true],
	expected [Your address] but found [YOUR ADDRESS]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.testcases.LoginApplicationTC1.Login(LoginApplicationTC1.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
      </class> <!-- com.testcases.LoginApplicationTC1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
